debug: true
server:
  port: 443
  context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  ssl:
    enabled: true
    key-store: /home/tomcat/apache-tomcat-8.5.8/cert/your-name.jks
    key-password: 19930308you
    key-store-type: JKS
    key-alias: 1
spring:
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  mvc:
    view:
      prefix: /
      suffix: .html
config:
  model:
    model-list:
      - name: root
        url: http://www.baidu.com
      - name: tally
        url: http://localhost:8080/tally/